version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - /home/ubuntu/nextcloud/database/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "nextcloud"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "nextcloud"
  nextcloud:
    image: nextcloud:29-apache
    restart: always
    depends_on:
      - db
      - nginx
    volumes:
      - /home/ubuntu/nextcloud/var/www/html:/var/www/html
    environment:
      NEXTCLOUD_ADMIN_USER: "admin"
      NEXTCLOUD_ADMIN_PASSWORD: "admin"
      POSTGRES_USER: "nextcloud"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "nextcloud"
      POSTGRES_HOST: "db"
      NEXTCLOUD_TRUSTED_DOMAINS: 158.160.103.235 test.vvot02.itiscl.ru
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/nextcloud/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/nextcloud/nginx/certbot-www:/var/www/certbot
      - /home/ubuntu/nextcloud/letsencrypt/certs:/etc/letsencrypt

networks:
  nextcloud-net:
    driver: bridge